# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbotlog',
            name='archived_path',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='아카이브 경로'),
        ),
    ]
