# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0002_pbotlog_archived_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbotlog',
            name='archived_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='아카이브 경로'),
        ),
    ]
